package com.codex.lle;

/** Explicit tuning for the two Sony reconstructions; final unlock clocks are not configurable. */
final class EffectWorkshopSonyParameters {
    private EffectWorkshopSonyParameters() {}
    static EffectWorkshopConfig.Parameter[] parametersFor(int effect) {
        if (effect == 35) return new EffectWorkshopConfig.Parameter[]{
            EffectWorkshopConfig.Parameter.integer("strip_count", "Strip count", "Geometry",17.0f,5.0f,40.0f,1.0f, "", "Sets the number of horizontal strips. Higher values produce narrower strips."),
            EffectWorkshopConfig.Parameter.number("affected_range", "Deformation window", "Geometry",5f / 17f,0.05f,0.8f,0.01f, "altezza", "Sets the fraction of screen height around the touch that can deform. Higher values affect more strips."),
            EffectWorkshopConfig.Parameter.number("fold_intensity", "Fold amplitude", "Geometry",1.0f,0.2f,2.0f,0.05f, "x", "Sets the spring's target fold amount while pressed. Higher values produce deeper folds."),
            EffectWorkshopConfig.Parameter.number("horizontal_fold", "Horizontal rotation", "Geometry",3.0f,0.0f,12.0f,0.5f, "degrees", "Sets the horizontal strip rotation multiplier, also weighted by horizontal touch position and fold amount."),
            EffectWorkshopConfig.Parameter.number("camera_fold", "Camera rotation", "Geometry",17.0f,0.0f,40.0f,1.0f, "degrees", "Sets the 3D rotation multiplier for strip waves. Higher values tilt folded strips more strongly."),
            EffectWorkshopConfig.Parameter.number("camera_depth", "Camera depth", "Geometry",3.0f,0.0f,8.0f,0.1f, "", "Sets the 3D translation multiplier applied to each folded strip."),
            EffectWorkshopConfig.Parameter.number("shade_strength", "Fold contrast", "Appearance",2.0f,0.0f,4.0f,0.1f, "", "Sets how strongly strip waves brighten or darken their sampled image. Zero removes fold shading."),
            EffectWorkshopConfig.Parameter.number("shadow_length", "Shadow length", "Appearance",50.0f,0.0f,150.0f,5.0f, "px", "Sets the maximum strip shadow length in pixels, reduced toward the deformation window's edges."),
            EffectWorkshopConfig.Parameter.number("shadow_threshold", "Shadow threshold", "Appearance",0.5f,0.0f,1.5f,0.05f, "", "Sets the spring-position threshold above which strip shadows are drawn. Higher values delay their appearance."),
            EffectWorkshopConfig.Parameter.number("shadow_alpha", "Shadow opacity", "Appearance",187f / 255f,0.0f,1.0f,0.05f, "", "Sets the opacity at the start of each strip's shadow gradient."),
            EffectWorkshopConfig.Parameter.number("seam_width", "Seam width", "Appearance",2.0f,0.0f,6.0f,0.1f, "px", "Sets strip seam stroke width in pixels. A zero-width Android stroke remains a one-pixel hairline."),
            EffectWorkshopConfig.Parameter.number("seam_threshold", "Seam threshold", "Appearance",0.1f,0.0f,1.0f,0.05f, "", "Sets the fold amount above which seams are drawn. Higher values hide seams on shallower folds."),
            EffectWorkshopConfig.Parameter.number("seam_opacity", "Seam opacity", "Appearance",1.0f,0.0f,1.0f,0.05f, "", "Multiplies seam opacity after strip fading. Zero hides seams."),
            EffectWorkshopConfig.Parameter.number("strip_opacity", "Strip opacity", "Appearance",1.0f,0.0f,1.0f,0.05f, "", "Multiplies folded-strip opacity and the seam opacity derived from it. Zero hides both."),
            EffectWorkshopConfig.Parameter.number("spring_stiffness", "Spring stiffness", "Physics",400.0f,50.0f,1200.0f,10.0f, "", "Sets how strongly the fold spring responds to its target. Higher values give faster motion."),
            EffectWorkshopConfig.Parameter.number("spring_damping", "Spring damping", "Physics",0.85f,0.05f,0.99f,0.01f, "", "Sets the fold spring's damping ratio. Higher values reduce bouncing."),
            EffectWorkshopConfig.Parameter.integer("hint_hold_ms", "Hint press duration", "Animation",130.0f,20.0f,1000.0f,10.0f, "ms", "Sets how long the simulated hint press stays held before release."),
            EffectWorkshopConfig.Parameter.number("sound_gain", "Sound volume", "Audio",1.0f,0.0f,1.0f,0.05f, "", "Sets touch and release sound volume. Zero mutes the sounds."),
        };
        if (effect == 36) return new EffectWorkshopConfig.Parameter[]{
            EffectWorkshopConfig.Parameter.number("card_scale", "Card scale", "Geometry",1.0f,0.5f,1.1f,0.05f, "x", "Scales card geometry around its center before perspective rotation."),
            EffectWorkshopConfig.Parameter.number("card_x", "Card horizontal offset", "Geometry",0.0f,-0.2f,0.2f,0.01f, "clip", "Moves card geometry horizontally in normalized clip coordinates before rotation."),
            EffectWorkshopConfig.Parameter.number("card_y", "Card vertical offset", "Geometry",0.0f,-0.2f,0.2f,0.01f, "clip", "Moves card geometry vertically in normalized clip coordinates before rotation."),
            EffectWorkshopConfig.Parameter.number("box_depth", "Glass depth", "Geometry",0.045f,0.005f,0.15f,0.005f, "clip", "Sets the depth separating the front and back card faces. Higher values make the glass edge thicker."),
            EffectWorkshopConfig.Parameter.number("corner_radius", "Corner radius", "Geometry",0.07f,0.0f,0.25f,0.01f, "clip", "Sets the rounded corner radius in clip coordinates, limited by card dimensions."),
            EffectWorkshopConfig.Parameter.integer("corner_segments", "Corner segments", "Geometry",8.0f,3.0f,24.0f,1.0f, "", "Sets the number of mesh segments per rounded corner. Higher values make the outline smoother."),
            EffectWorkshopConfig.Parameter.number("center_sensitivity", "Touch position sensitivity", "Motion",0.02f,0.0f,0.1f,0.005f, "degrees/px", "Sets initial rotation per pixel away from the screen center. Zero removes position-based initial rotation."),
            EffectWorkshopConfig.Parameter.number("drag_sensitivity", "Drag sensitivity", "Motion",0.44f,0.05f,1.0f,0.01f, "degrees/px", "Sets target rotation per pixel of horizontal drag, limited by the maximum angle."),
            EffectWorkshopConfig.Parameter.number("drag_speed", "Maximum drag speed", "Motion",0.9f,0.05f,2.0f,0.05f, "degrees/ms", "Caps how quickly rotation approaches the drag target in degrees per millisecond."),
            EffectWorkshopConfig.Parameter.number("initial_speed", "Initial rotation speed", "Motion",0.13f,0.01f,1.0f,0.01f, "degrees/ms", "Sets how quickly the card approaches the rotation determined by the initial touch position."),
            EffectWorkshopConfig.Parameter.number("drag_slop", "Drag threshold", "Motion",20.0f,0.0f,80.0f,1.0f, "px", "Sets horizontal movement required before drag tracking takes over from initial rotation."),
            EffectWorkshopConfig.Parameter.number("max_angle", "Maximum drag rotation", "Motion",179.0f,10.0f,179.0f,1.0f, "degrees", "Limits rotation during initial positioning and dragging. The final unlock turn still completes to 180 degrees."),
            EffectWorkshopConfig.Parameter.number("cancel_speed", "Cancel bounce speed", "Motion",1.0f,0.25f,2.0f,0.05f, "x", "Multiplies rotation speed during the cancellation bounce."),
            EffectWorkshopConfig.Parameter.number("cancel_decay", "Cancel bounce attenuation", "Motion",1.0f,0.25f,2.0f,0.05f, "x", "Multiplies the amplitude removed at each cancellation bounce. Higher values settle sooner."),
            EffectWorkshopConfig.Parameter.integer("entry_ms", "Appearance duration", "Animation",140.0f,20.0f,500.0f,10.0f, "ms", "Sets how long card and underlay opacity take to rise when the gesture or hint begins."),
            EffectWorkshopConfig.Parameter.integer("hint_ms", "Hint duration", "Animation",480.0f,100.0f,1500.0f,10.0f, "ms", "Sets the duration of the card's oscillating hint."),
            EffectWorkshopConfig.Parameter.number("hint_angle", "Hint amplitude", "Animation",9.0f,0.0f,45.0f,1.0f, "degrees", "Sets the peak rotation multiplier of the hint. Zero removes hint rotation."),
            EffectWorkshopConfig.Parameter.number("hint_cycles", "Hint oscillations", "Animation",1.0f,0.5f,3.0f,0.1f, "", "Sets how many rotation cycles fit within the hint duration."),
            EffectWorkshopConfig.Parameter.number("exit_scale", "Final card scale", "Geometry",0.84f,0.3f,1.0f,0.01f, "x", "Sets the card's ending scale during its fixed-duration unlock fade."),
            EffectWorkshopConfig.Parameter.number("camera_distance", "Perspective distance", "Optics",2.6f,2.0f,5.0f,0.1f, "", "Sets perspective camera distance. Higher values reduce the perspective size change during rotation."),
            EffectWorkshopConfig.Parameter.number("border_rounding", "Rim rounding", "Optics",0.035f,0.0f,0.1f,0.005f, "short side", "Sets the shader border's corner radius as a fraction of the texture's shorter side."),
            EffectWorkshopConfig.Parameter.number("border_width", "Rim width", "Optics",6.0f,0.5f,20.0f,0.5f, "px", "Sets the width in texture pixels over which the border light fades inward."),
            EffectWorkshopConfig.Parameter.number("front_rim", "Front rim light", "Optics",0.76f,0.0f,1.0f,0.02f, "", "Sets how strongly the front border blends toward its configured tint."),
            EffectWorkshopConfig.Parameter.number("back_rim", "Back rim light", "Optics",0.68f,0.0f,1.0f,0.02f, "", "Sets how strongly the back border blends toward its configured tint."),
            EffectWorkshopConfig.Parameter.number("blur_radius", "Frosted-glass blur radius", "Optics",1.25f,0.0f,4.0f,0.05f, "px", "Sets texture sample offsets for the back face's blur in texture pixels. Zero samples the same point."),
            EffectWorkshopConfig.Parameter.number("blur_mix", "Frosted-glass blend", "Optics",0.2f,0.0f,1.0f,0.02f, "", "Blends the back face between its sharp and blurred samples. Zero keeps it sharp; one uses the blurred result."),
            EffectWorkshopConfig.Parameter.number("face_ambient", "Back-face ambient light", "Optics",0.72f,0.0f,1.0f,0.02f, "", "Sets the constant lighting contribution on the back face."),
            EffectWorkshopConfig.Parameter.number("face_angular", "Back-face rotation light", "Optics",0.28f,0.0f,1.0f,0.02f, "", "Sets the back-face lighting contribution weighted by the absolute cosine of rotation."),
            EffectWorkshopConfig.Parameter.number("tint_r", "Rim tint R", "Color",0.94f,0.0f,1.0f,0.02f, "", "Sets the red component of the front and back rim tint."),
            EffectWorkshopConfig.Parameter.number("tint_g", "Rim tint G", "Color",0.98f,0.0f,1.0f,0.02f, "", "Sets the green component of the front and back rim tint."),
            EffectWorkshopConfig.Parameter.number("tint_b", "Rim tint B", "Color",1.0f,0.0f,1.0f,0.02f, "", "Sets the blue component of the front and back rim tint."),
            EffectWorkshopConfig.Parameter.number("edge_r", "Edge tint R", "Color",0.78f,0.0f,1.0f,0.02f, "", "Sets the red component of the glass-edge tint."),
            EffectWorkshopConfig.Parameter.number("edge_g", "Edge tint G", "Color",0.92f,0.0f,1.0f,0.02f, "", "Sets the green component of the glass-edge tint."),
            EffectWorkshopConfig.Parameter.number("edge_b", "Edge tint B", "Color",1.0f,0.0f,1.0f,0.02f, "", "Sets the blue component of the glass-edge tint."),
            EffectWorkshopConfig.Parameter.number("glint_frequency", "Glint frequency", "Optics",55.0f,5.0f,100.0f,1.0f, "", "Sets how many brightness variations run along the glass edge texture coordinates."),
            EffectWorkshopConfig.Parameter.number("glint_rotation", "Glint rotation motion", "Optics",3.0f,0.0f,8.0f,0.1f, "", "Sets how strongly card rotation shifts the edge's glint pattern. Zero removes this shift."),
            EffectWorkshopConfig.Parameter.number("glint_power", "Glint concentration", "Optics",10.0f,1.0f,32.0f,1.0f, "", "Sets the exponent of edge glints. Higher values produce narrower bright peaks."),
            EffectWorkshopConfig.Parameter.number("edge_ambient", "Edge ambient light", "Optics",0.78f,0.0f,1.0f,0.02f, "", "Sets the constant lighting contribution on the glass edge."),
            EffectWorkshopConfig.Parameter.number("edge_angular", "Edge rotation light", "Optics",0.22f,0.0f,1.0f,0.02f, "", "Sets the edge lighting contribution weighted by the absolute sine of rotation."),
            EffectWorkshopConfig.Parameter.number("edge_base", "Edge base brightness", "Optics",0.82f,0.0f,1.0f,0.02f, "", "Sets the constant brightness multiplier of the glass edge."),
            EffectWorkshopConfig.Parameter.number("edge_glint", "Edge glint intensity", "Optics",0.18f,0.0f,1.0f,0.02f, "", "Sets the additional edge brightness contributed by glints."),
            EffectWorkshopConfig.Parameter.number("edge_alpha", "Edge opacity", "Optics",0.88f,0.0f,1.0f,0.02f, "", "Sets glass-edge opacity before the card's global fade."),
            EffectWorkshopConfig.Parameter.number("tile_opacity", "Card opacity", "Appearance",1.0f,0.0f,1.0f,0.05f, "", "Multiplies front, back and edge opacity after the card's animation fade. Zero hides the card."),
            EffectWorkshopConfig.Parameter.number("underlay_opacity", "Last screen opacity", "Appearance",1.0f,0.0f,1.0f,0.05f, "", "Multiplies the secondary screen image's opacity after its animation fade."),
            EffectWorkshopConfig.Parameter.number("sound_gain", "Sound volume", "Audio",1.0f,0.0f,1.0f,0.05f, "", "Sets the unlock sound volume. Zero mutes the sound."),
        };
        return new EffectWorkshopConfig.Parameter[0];
    }
}
