package com.codex.lle;

/** Exact JNI array order; see the per-port WORKSHOP.md files. Values are immutable snapshots. */
final class EffectWorkshopDropsParameters {
    private EffectWorkshopDropsParameters() {}
    private static EffectWorkshopConfig.Parameter[] colour() { return new EffectWorkshopConfig.Parameter[] {
        EffectWorkshopConfig.Parameter.number("radius_scale", "Fluid interaction radius", "Fluid motion", 1.0f, 0.5f, 1.5f, 0.05f, "x", "Higher values enlarge each fluid particle and its interaction area; lower values make the drop finer and more compact."),
        EffectWorkshopConfig.Parameter.number("density_scale", "Fluid target density", "Fluid motion", 1.0f, 0.5f, 1.5f, 0.05f, "x", "Changes the density the fluid tries to maintain. Higher values allow a denser cluster before pressure pushes its particles apart; lower values spread them more readily."),
        EffectWorkshopConfig.Parameter.number("viscosity_scale", "Fluid viscosity", "Fluid motion", 1.0f, 0.0f, 2.0f, 0.05f, "x", "Higher values reduce differences in particle speed and make the fluid move more cohesively. Lower values let particles slide and separate more freely."),
        EffectWorkshopConfig.Parameter.number("pressure_scale", "Fluid pressure", "Fluid motion", 1.0f, 0.0f, 1.5f, 0.05f, "x", "Higher values strengthen the pressure that separates crowded particles; lower values make the fluid softer and easier to compress."),
        EffectWorkshopConfig.Parameter.number("near_pressure_scale", "Close-range pressure", "Fluid motion", 1.0f, 0.0f, 1.5f, 0.05f, "x", "Higher values push very close particles apart more strongly. Lower values allow tighter clusters within the drop."),
        EffectWorkshopConfig.Parameter.number("growth_scale", "Drop growth speed", "Fluid motion", 1.0f, 0.5f, 1.5f, 0.05f, "x", "Higher values bring newly emitted fluid particles to their full size sooner; lower values make their growth more gradual."),
        EffectWorkshopConfig.Parameter.number("edge_bounce", "Screen-edge bounce", "Fluid motion", 0.15f, 0.0f, 0.6f, 0.01f, "factor", "Higher values make particles rebound more strongly from the screen edges. Zero removes the returning bounce."),
        EffectWorkshopConfig.Parameter.number("tilt_x_scale", "Horizontal tilt response", "Fluid motion", 1.0f, 0.0f, 2.0f, 0.05f, "x", "Scales horizontal fluid acceleration from the tilt sensor. Higher values make tilting move the drop more strongly; zero disables this axis."),
        EffectWorkshopConfig.Parameter.number("tilt_y_scale", "Vertical tilt response", "Fluid motion", 1.0f, 0.0f, 2.0f, 0.05f, "x", "Scales vertical fluid acceleration from the tilt sensor. Higher values make tilting move the drop more strongly; zero disables this axis."),
        EffectWorkshopConfig.Parameter.number("refraction_scale", "Refraction strength", "Optics", 1.0f, 0.0f, 2.0f, 0.05f, "x", "Higher values bend the background image more strongly through the drop. Zero removes this image displacement, while the drop outline and other optical layers remain."),
        EffectWorkshopConfig.Parameter.number("shadow_width", "Inner shadow width", "Optics", 0.6f, 0.0f, 1.2f, 0.02f, "factor", "Higher values widen the dark inner rim of Colour Droplet; lower values narrow it. This changes its optical shading rather than fluid motion."),
        EffectWorkshopConfig.Parameter.number("saturation", "Colour saturation", "Optics", 1.3f, 0.0f, 2.0f, 0.05f, "factor", "Higher values make the colours sampled through Colour Droplet more vivid. Zero removes colour saturation inside the drop."),
        EffectWorkshopConfig.Parameter.number("brightness", "Colour brightness", "Optics", 1.3f, 0.5f, 2.0f, 0.05f, "factor", "Higher values brighten the colours sampled through Colour Droplet; lower values darken them. The result depends on the background image."),
        EffectWorkshopConfig.Parameter.number("minimum_value", "Minimum colour brightness", "Optics", 0.15f, 0.0f, 0.5f, 0.01f, "factor", "Raises the minimum brightness used for Colour Droplet colour samples. Higher values keep dark background colours more visible inside the drop."),
    }; }
    private static EffectWorkshopConfig.Parameter[] s6_water() { return new EffectWorkshopConfig.Parameter[] {
        EffectWorkshopConfig.Parameter.number("radius_scale", "Fluid interaction radius", "Fluid motion", 1.0f, 0.5f, 1.5f, 0.05f, "x", "Higher values enlarge each fluid particle and its interaction area; lower values make the drop finer and more compact."),
        EffectWorkshopConfig.Parameter.number("density_scale", "Fluid target density", "Fluid motion", 1.0f, 0.5f, 1.5f, 0.05f, "x", "Changes the density the fluid tries to maintain. Higher values allow a denser cluster before pressure pushes its particles apart; lower values spread them more readily."),
        EffectWorkshopConfig.Parameter.number("viscosity_scale", "Fluid viscosity", "Fluid motion", 1.0f, 0.0f, 2.0f, 0.05f, "x", "Higher values reduce differences in particle speed and make the fluid move more cohesively. Lower values let particles slide and separate more freely."),
        EffectWorkshopConfig.Parameter.number("pressure_scale", "Fluid pressure", "Fluid motion", 1.0f, 0.0f, 1.5f, 0.05f, "x", "Higher values strengthen the pressure that separates crowded particles; lower values make the fluid softer and easier to compress."),
        EffectWorkshopConfig.Parameter.number("near_pressure_scale", "Close-range pressure", "Fluid motion", 1.0f, 0.0f, 1.5f, 0.05f, "x", "Higher values push very close particles apart more strongly. Lower values allow tighter clusters within the drop."),
        EffectWorkshopConfig.Parameter.number("growth_scale", "Drop growth speed", "Fluid motion", 1.0f, 0.5f, 1.5f, 0.05f, "x", "Higher values bring newly emitted fluid particles to their full size sooner; lower values make their growth more gradual."),
        EffectWorkshopConfig.Parameter.number("edge_bounce", "Screen-edge bounce", "Fluid motion", 0.15f, 0.0f, 0.6f, 0.01f, "factor", "Higher values make particles rebound more strongly from the screen edges. Zero removes the returning bounce."),
        EffectWorkshopConfig.Parameter.number("tilt_x_scale", "Horizontal tilt response", "Fluid motion", 1.0f, 0.0f, 2.0f, 0.05f, "x", "Scales horizontal fluid acceleration from the tilt sensor. Higher values make tilting move the drop more strongly; zero disables this axis."),
        EffectWorkshopConfig.Parameter.number("tilt_y_scale", "Vertical tilt response", "Fluid motion", 1.0f, 0.0f, 2.0f, 0.05f, "x", "Scales vertical fluid acceleration from the tilt sensor. Higher values make tilting move the drop more strongly; zero disables this axis."),
        EffectWorkshopConfig.Parameter.number("refraction_scale", "Refraction strength", "Optics", 1.0f, 0.0f, 2.0f, 0.05f, "x", "Higher values bend the background image more strongly through the drop. Zero removes this image displacement, while the drop outline and other optical layers remain."),
        EffectWorkshopConfig.Parameter.number("density_threshold", "Visible fluid threshold", "Optics", 0.5f, 0.25f, 0.8f, 0.01f, "factor", "Higher values require a denser part of the fluid field to show the solid drop, making its visible outline smaller. Lower values reveal more of the thin fluid around its edge."),
        EffectWorkshopConfig.Parameter.number("edge_offset", "Optical rim width", "Optics", 0.075f, 0.0f, 0.15f, 0.005f, "factor", "Higher values widen the highlighted optical rim around the S6 Water Droplet. Lower values confine the rim closer to the visible fluid boundary."),
        EffectWorkshopConfig.Parameter.number("shadow_offset", "Shadow softness", "Optics", 0.15f, 0.0f, 0.3f, 0.01f, "factor", "Changes how quickly the S6 Water Droplet shadow reaches its darkest opacity. Higher values soften that transition; lower values make the shadow reach full strength sooner."),
        EffectWorkshopConfig.Parameter.number("shadow_range", "Shadow displacement", "Optics", 12.0f, 0.0f, 24.0f, 0.5f, "factor", "Higher values move the S6 Water Droplet shadow farther from the visible drop. Zero removes this directional shadow displacement."),
        EffectWorkshopConfig.Parameter.number("refraction_eta", "Refraction ratio", "Optics", 0.75001875f, 0.5f, 1.0f, 0.01f, "factor", "Changes the bending angle used to sample the background through S6 Water Droplet. Values closer to one reduce bending; lower values produce stronger distortion for the same fluid surface."),
        EffectWorkshopConfig.Parameter.number("refraction_amplitude", "Refraction displacement", "Optics", 0.075f, 0.0f, 0.15f, 0.005f, "factor", "Higher values increase the background displacement produced by the S6 Water Droplet optical surface. Zero removes that displacement."),
    }; }
    private static EffectWorkshopConfig.Parameter[] spark() { return new EffectWorkshopConfig.Parameter[] {
        EffectWorkshopConfig.Parameter.integer("press_count", "Touch particle count", "Emission", 1100.0f, 1.0f, 1100.0f, 1.0f, "particles", "Higher values create a denser touch burst; lower values emit fewer bubbles. The touch count applies to its own emission group."),
        EffectWorkshopConfig.Parameter.integer("hint_count", "Hint particle count", "Emission", 1100.0f, 1.0f, 1100.0f, 1.0f, "particles", "Higher values create a denser hint burst; lower values emit fewer bubbles. The hint count applies to its own emission group."),
        EffectWorkshopConfig.Parameter.number("press_small_radius_min", "Touch small minimum emission radius", "Emission", 40.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the minimum random starting distance of small bubbles emitted by a touch from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("press_small_radius_max", "Touch small maximum emission radius", "Emission", 250.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the maximum random starting distance of small bubbles emitted by a touch from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("press_medium_radius_min", "Touch medium minimum emission radius", "Emission", 10.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the minimum random starting distance of medium bubbles emitted by a touch from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("press_medium_radius_max", "Touch medium maximum emission radius", "Emission", 220.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the maximum random starting distance of medium bubbles emitted by a touch from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("press_large_radius_min", "Touch large minimum emission radius", "Emission", 10.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the minimum random starting distance of large bubbles emitted by a touch from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("press_large_radius_max", "Touch large maximum emission radius", "Emission", 240.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the maximum random starting distance of large bubbles emitted by a touch from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("hint_small_radius_min", "Hint small minimum emission radius", "Emission", 30.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the minimum random starting distance of small bubbles emitted by the hint from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("hint_small_radius_max", "Hint small maximum emission radius", "Emission", 250.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the maximum random starting distance of small bubbles emitted by the hint from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("hint_medium_radius_min", "Hint medium minimum emission radius", "Emission", 10.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the minimum random starting distance of medium bubbles emitted by the hint from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("hint_medium_radius_max", "Hint medium maximum emission radius", "Emission", 220.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the maximum random starting distance of medium bubbles emitted by the hint from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("hint_large_radius_min", "Hint large minimum emission radius", "Emission", 10.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the minimum random starting distance of large bubbles emitted by the hint from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("hint_large_radius_max", "Hint large maximum emission radius", "Emission", 200.0f, 0.0f, 400.0f, 5.0f, "px @1440", "Sets the maximum random starting distance of large bubbles emitted by the hint from the emission point. Higher values spread the burst farther outward; lower values start it closer to the centre."),
        EffectWorkshopConfig.Parameter.number("small_size_min", "Small minimum initial size", "Size", 4.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the minimum initial size of small bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("small_size_max", "Small maximum initial size", "Size", 10.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the maximum initial size of small bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("medium_size_min", "Medium minimum initial size", "Size", 12.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the minimum initial size of medium bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("medium_size_max", "Medium maximum initial size", "Size", 18.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the maximum initial size of medium bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("medium_target_size_min", "Medium minimum grown size", "Size", 12.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the minimum grown size of medium bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("medium_target_size_max", "Medium maximum grown size", "Size", 25.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the maximum grown size of medium bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("large_size_min", "Large minimum initial size", "Size", 24.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the minimum initial size of large bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("large_size_max", "Large maximum initial size", "Size", 28.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the maximum initial size of large bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("large_target_size_min", "Large minimum grown size", "Size", 28.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the minimum grown size of large bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("large_target_size_max", "Large maximum grown size", "Size", 43.0f, 1.0f, 80.0f, 1.0f, "px @1440", "Sets the maximum grown size of large bubbles. Higher values make those bubbles larger; lower values make them smaller."),
        EffectWorkshopConfig.Parameter.number("press_lifetime_min", "Touch minimum lifetime", "Animation", 2.2f, 0.5f, 5.0f, 0.1f, "s", "Sets the minimum random lifetime of touch bubbles. Higher values keep them alive longer; lower values make the burst clear sooner."),
        EffectWorkshopConfig.Parameter.number("press_lifetime_max", "Touch maximum lifetime", "Animation", 2.5f, 0.5f, 5.0f, 0.1f, "s", "Sets the maximum random lifetime of touch bubbles. Higher values keep them alive longer; lower values make the burst clear sooner."),
        EffectWorkshopConfig.Parameter.number("hint_small_lifetime_min", "Hint small minimum lifetime", "Animation", 2.0f, 0.5f, 5.0f, 0.1f, "s", "Sets the minimum random lifetime of small bubbles emitted by the hint. Higher values keep them alive longer; lower values make the burst clear sooner."),
        EffectWorkshopConfig.Parameter.number("hint_small_lifetime_max", "Hint small maximum lifetime", "Animation", 2.5f, 0.5f, 5.0f, 0.1f, "s", "Sets the maximum random lifetime of small bubbles emitted by the hint. Higher values keep them alive longer; lower values make the burst clear sooner."),
        EffectWorkshopConfig.Parameter.number("hint_medium_lifetime_min", "Hint medium minimum lifetime", "Animation", 1.8f, 0.5f, 5.0f, 0.1f, "s", "Sets the minimum random lifetime of medium bubbles emitted by the hint. Higher values keep them alive longer; lower values make the burst clear sooner."),
        EffectWorkshopConfig.Parameter.number("hint_medium_lifetime_max", "Hint medium maximum lifetime", "Animation", 2.3f, 0.5f, 5.0f, 0.1f, "s", "Sets the maximum random lifetime of medium bubbles emitted by the hint. Higher values keep them alive longer; lower values make the burst clear sooner."),
        EffectWorkshopConfig.Parameter.number("hint_large_lifetime_min", "Hint large minimum lifetime", "Animation", 1.6f, 0.5f, 5.0f, 0.1f, "s", "Sets the minimum random lifetime of large bubbles emitted by the hint. Higher values keep them alive longer; lower values make the burst clear sooner."),
        EffectWorkshopConfig.Parameter.number("hint_large_lifetime_max", "Hint large maximum lifetime", "Animation", 2.1f, 0.5f, 5.0f, 0.1f, "s", "Sets the maximum random lifetime of large bubbles emitted by the hint. Higher values keep them alive longer; lower values make the burst clear sooner."),
        EffectWorkshopConfig.Parameter.number("medium_growth_min", "Medium minimum growth time", "Animation", 0.3f, 0.1f, 2.0f, 0.05f, "s", "Sets the minimum time taken by medium bubbles to reach their target size. Higher values slow growth; lower values make them grow sooner."),
        EffectWorkshopConfig.Parameter.number("medium_growth_max", "Medium maximum growth time", "Animation", 0.5f, 0.1f, 2.0f, 0.05f, "s", "Sets the maximum time taken by medium bubbles to reach their target size. Higher values slow growth; lower values make them grow sooner."),
        EffectWorkshopConfig.Parameter.number("large_growth_min", "Large minimum growth time", "Animation", 0.3f, 0.1f, 2.0f, 0.05f, "s", "Sets the minimum time taken by large bubbles to reach their target size. Higher values slow growth; lower values make them grow sooner."),
        EffectWorkshopConfig.Parameter.number("large_growth_max", "Large maximum growth time", "Animation", 0.7f, 0.1f, 2.0f, 0.05f, "s", "Sets the maximum time taken by large bubbles to reach their target size. Higher values slow growth; lower values make them grow sooner."),
        EffectWorkshopConfig.Parameter.number("press_alpha_min", "Touch minimum opacity", "Optics", 0.35f, 0.0f, 1.0f, 0.05f, "factor", "Sets the minimum random opacity of small and medium touch bubbles. Higher values make them more visible; lower values make them more transparent."),
        EffectWorkshopConfig.Parameter.number("press_alpha_max", "Touch maximum opacity", "Optics", 0.6f, 0.0f, 1.0f, 0.05f, "factor", "Sets the maximum random opacity of small and medium touch bubbles. Higher values make them more visible; lower values make them more transparent."),
        EffectWorkshopConfig.Parameter.number("press_large_alpha_min", "Touch large minimum opacity", "Optics", 0.25f, 0.0f, 1.0f, 0.05f, "factor", "Sets the minimum random opacity of large bubbles emitted by a touch. Higher values make them more visible; lower values make them more transparent."),
        EffectWorkshopConfig.Parameter.number("press_large_alpha_max", "Touch large maximum opacity", "Optics", 0.6f, 0.0f, 1.0f, 0.05f, "factor", "Sets the maximum random opacity of large bubbles emitted by a touch. Higher values make them more visible; lower values make them more transparent."),
        EffectWorkshopConfig.Parameter.number("hint_alpha_min", "Hint minimum opacity", "Optics", 0.5f, 0.0f, 1.0f, 0.05f, "factor", "Sets the minimum random opacity of hint bubbles. Higher values make them more visible; lower values make them more transparent."),
        EffectWorkshopConfig.Parameter.number("hint_alpha_max", "Hint maximum opacity", "Optics", 0.6f, 0.0f, 1.0f, 0.05f, "factor", "Sets the maximum random opacity of hint bubbles. Higher values make them more visible; lower values make them more transparent."),
        EffectWorkshopConfig.Parameter.number("speed_min", "Minimum radial speed", "Fluid motion", 0.01f, 0.0f, 0.08f, 0.002f, "factor", "Sets the minimum random radial speed of the bubbles. Higher values move them outward more quickly; lower values keep them near their emission position longer."),
        EffectWorkshopConfig.Parameter.number("speed_max", "Maximum radial speed", "Fluid motion", 0.03f, 0.0f, 0.08f, 0.002f, "factor", "Sets the maximum random radial speed of the bubbles. Higher values move them outward more quickly; lower values keep them near their emission position longer."),
        EffectWorkshopConfig.Parameter.number("press_acceleration", "Touch edge acceleration", "Fluid motion", 0.6f, 0.0f, 2.0f, 0.05f, "factor", "Higher values accelerate touch bubbles more strongly near the screen edge. Zero removes this extra edge acceleration."),
        EffectWorkshopConfig.Parameter.number("hint_acceleration", "Hint edge acceleration", "Fluid motion", 1.0f, 0.0f, 2.0f, 0.05f, "factor", "Higher values accelerate hint bubbles more strongly near the screen edge. Zero removes this extra edge acceleration."),
        EffectWorkshopConfig.Parameter.number("edge_band_min", "Minimum edge-response band", "Fluid motion", 0.03f, 0.01f, 0.3f, 0.01f, "screen width", "Sets the minimum randomly chosen edge-response band as a fraction of screen width. Higher values begin edge acceleration farther from the edge; lower values confine it closer to the edge."),
        EffectWorkshopConfig.Parameter.number("edge_band_max", "Maximum edge-response band", "Fluid motion", 0.12f, 0.01f, 0.3f, 0.01f, "screen width", "Sets the maximum randomly chosen edge-response band as a fraction of screen width. Higher values begin edge acceleration farther from the edge; lower values confine it closer to the edge."),
    }; }
    static EffectWorkshopConfig.Parameter[] parametersFor(int effect) {
        switch (effect) {
        case 22: return spark();
        case 23: return colourWithoutTilt();
        case 24: return colour();
        case 26: return s6_water();
        default: return new EffectWorkshopConfig.Parameter[0];
        }
    }
    private static EffectWorkshopConfig.Parameter[] colourWithoutTilt() {
        EffectWorkshopConfig.Parameter[] all = colour();
        EffectWorkshopConfig.Parameter[] result = new EffectWorkshopConfig.Parameter[all.length - 2];
        int target = 0;
        for (EffectWorkshopConfig.Parameter parameter : all) {
            if (!"tilt_x_scale".equals(parameter.key) && !"tilt_y_scale".equals(parameter.key)) {
                result[target++] = parameter;
            }
        }
        return result;
    }
    static float[] pack(EffectWorkshopConfig.Values values) {
        // Both Colour variants share the native layout; the non-sensor variant
        // supplies the original tilt coefficients without advertising inert controls.
        EffectWorkshopConfig.Parameter[] schema = values.effect == 23 ? colour() : parametersFor(values.effect);
        float[] packed = new float[schema.length];
        for (int i = 0; i < packed.length; i++) {
            boolean hiddenTilt = values.effect == 23
                    && ("tilt_x_scale".equals(schema[i].key) || "tilt_y_scale".equals(schema[i].key));
            packed[i] = hiddenTilt ? schema[i].defaultValue : values.get(schema[i].key);
        }
        return packed;
    }
}
