package com.codex.lle;

/** Shader sources recovered from Samsung's Ripple Ink lineage, first proven on Note 3. */
final class RippleInkPortGlesShaders {
    /* Byte-identical shader body in the 88991 and secondary 04BE ELF variants. */
    static final String MESH_VERTEX =
            "uniform mat4 uMVPMatrix;\n"
            + "attribute vec4 aPosition;\n"
            + "attribute vec4 aHeights;\n"
            + "varying vec2 vWaterTextureCoord;\n"
            + "varying vec2 vBGTexture1Coord;\n"
            + "varying vec2 vBGScreenCoord;\n"
            + "varying vec3 vNormal;\n"
            + "varying vec3 vHalfVec;\n"
            + "varying float vHeights;\n"
            + "uniform float uMESH_SIZE_WIDTH;\n"
            + "uniform float uMESH_SIZE_HEIGHT;\n"
            + "uniform float uNUM_DETAILS_WIDTH;\n"
            + "uniform float uNUM_DETAILS_HEIGHT;\n"
            + "uniform float uRefractiveIndex;\n"
            + "void main() {\n"
            + "  float maxX = uMESH_SIZE_WIDTH / 2.0;\n"
            + "  float maxY = uMESH_SIZE_HEIGHT / 2.0;\n"
            + "  float rimo = uRefractiveIndex - 1.0;\n"
            + "  vec4 pos = aPosition;\n"
            + "  vec4 heights = aHeights;\n"
            + "  float len = heights.x;\n"
            + "  vec3 v = vec3(pos.x, pos.y, len * 0.25);\n"
            + "  vec2 n = (vec2(len) - heights.yz) * 0.25;\n"
            + "  float nz = sqrt(dot(n, n) + 1.0);\n"
            + "  n = n / nz;\n"
            + "  vec3 d = vec3(v.x, v.y, v.z + 30.0);\n"
            + "  len = sqrt(dot(d, d));\n"
            + "  d = d / len;\n"
            + "  vec3 preRefractionD = d;\n"
            + "  float t = dot(d, vec3(n.x, n.y, 1.0)) * rimo;\n"
            + "  d.x += n.x * t;\n"
            + "  d.y += n.y * t;\n"
            + "  float r0, u0, v0;\n"
            + "  r0 = (30.9 - v.z) / d.z;\n"
            + "  u0 = (d.x * r0 + v.x) / maxX * 0.25 + 0.5;\n"
            + "  v0 = (d.y * r0 + v.y) / maxY * -0.25 + 0.5;\n"
            + "  float screenU0 = (preRefractionD.x * r0 + v.x) / maxX * 0.25 + 0.5;\n"
            + "  float screenV0 = (preRefractionD.y * r0 + v.y) / maxY * -0.25 + 0.5;\n"
            + "  float uxx = n.x * 0.5 + 0.5 + pos.y / uMESH_SIZE_WIDTH * 0.25;\n"
            + "  float vxx = n.y * 0.5 + 0.5 + pos.x / uMESH_SIZE_HEIGHT * 0.25;\n"
            + "  vWaterTextureCoord = vec2(uxx, vxx);\n"
            + "  vBGTexture1Coord = vec2(u0, v0);\n"
            + "  vBGScreenCoord = vec2(screenU0, screenV0);\n"
            + "  vNormal = normalize(vec3(n.x, n.y, 0.6));\n"
            + "  vHalfVec = normalize(normalize(vec3(0.0, 0.0, 1.0)"
            + " - (uMVPMatrix * pos).xyz)"
            + " + (uMVPMatrix * vec4(5.0, -5.0, 1.0, 1.0)).xyz);\n"
            + "  vHeights = aHeights.x;\n"
            + "  gl_Position = uMVPMatrix * pos;\n"
            + "}\n";

    static final String FULLSCREEN_VERTEX =
            "attribute vec4 vertex;\n"
            + "attribute vec2 texCoord;\n"
            + "varying vec2 v_texCoord;\n"
            + "void main() {\n"
            + "  gl_Position = vertex;\n"
            + "  v_texCoord = texCoord;\n"
            + "}\n";

    static final String STOCK_ADVECT_DENSITY_FRAGMENT =
            "precision mediump float;\n"
            + "uniform sampler2D VelocityTexture;\n"
            + "uniform sampler2D SourceTexture;\n"
            + "uniform vec2 TimeStep;\n"
            + "uniform float BackwardStepSize;\n"
            + "uniform float Dissipation;\n"
            + "uniform vec2 Scale;\n"
            + "uniform vec2 center;\n"
            + "uniform int drag;\n"
            + "varying vec2 v_texCoord;\n"
            + "vec2 encode(float v) {\n"
            + "  const vec2 mask = vec2(0.00392157, 1.0);\n"
            + "  v = clamp(v, -127.0, 127.0);\n"
            + "  vec2 p = fract(v * mask);\n"
            + "  p.x -= p.y / 255.0;\n"
            + "  return p;\n"
            + "}\n"
            + "void main() {\n"
            + "  vec4 buf = texture2D(VelocityTexture, v_texCoord);\n"
            + "  vec2 u;\n"
            + "  u.x = 255.0 * buf.x + buf.y - 127.0;\n"
            + "  u.y = 255.0 * buf.z + buf.w - 127.0;\n"
            + "  float back_step = BackwardStepSize;\n"
            + "  if (drag < 2) {\n"
            + "    float d = distance(center, Scale * v_texCoord);\n"
            + "    if (d < 80.0) back_step = 0.0075 * d;\n"
            + "  }\n"
            + "  vec2 coord = v_texCoord - back_step * TimeStep * u;\n"
            + "  buf = texture2D(SourceTexture, coord);\n"
            + "  float value = 255.0 * buf.x + buf.y;\n"
            + "  gl_FragColor.xy = encode(Dissipation * value);\n"
            + "}\n";

    static final String STOCK_ADD_INK_FRAGMENT =
            "precision mediump float;\n"
            + "uniform sampler2D Source;\n"
            + "uniform vec2 Scale;\n"
            + "uniform vec2 current;\n"
            + "uniform vec2 previous;\n"
            + "uniform vec2 normal;\n"
            + "uniform int mode;\n"
            + "uniform float len;\n"
            + "uniform float ImpulseDensity;\n"
            + "uniform float Radius;\n"
            + "varying vec2 v_texCoord;\n"
            + "vec2 encode(float v) {\n"
            + "  v = clamp(v, -127.0, 127.0);\n"
            + "  vec2 p;\n"
            + "  p.x = fract(v / 255.0);\n"
            + "  p.y = fract(v);\n"
            + "  p.x -= p.y / 255.0;\n"
            + "  return p;\n"
            + "}\n"
            + "void main() {\n"
            + "  vec4 buf = texture2D(Source, v_texCoord);\n"
            + "  float x = 255.0 * buf.x + buf.y;\n"
            + "  vec2 p = Scale * v_texCoord;\n"
            + "  if (mode == 2) {\n"
            + "    vec2 vector = p - previous;\n"
            + "    float dot_val = dot(normal, vector);\n"
            + "    if (dot_val > 0.0 && dot_val < len) {\n"
            + "      vec2 projected = previous + dot_val * normal;\n"
            + "      float d = distance(projected, p);\n"
            + "      if (d < Radius)"
            + " x += ImpulseDensity * exp(-d*d/(0.8*Radius*Radius));\n"
            + "    }\n"
            + "  } else {\n"
            + "    float d = distance(current, p);\n"
            + "    if (d < Radius) x += ImpulseDensity / (1.0 + d);\n"
            + "  }\n"
            + "  gl_FragColor.xy = encode(x);\n"
            + "}\n";

    /**
     * Transparent-overlay translation of the recovered ink mesh fragment.
     *
     * <p>The stock fragment owns an opaque lockscreen. The app-owned port first forms the accepted
     * slope-masked water colour over a nonrefracted background sample, applies Samsung's ink delta,
     * then emits the exact minimum premultiplied layer that reconstructs that target over the same
     * nonrefracted sample. The palette uniform carries raw finite S4 RGB and uses the recovered
     * stock ink weight directly. The navy zero-red slot never uploads infinity and the
     * zero-density branch remains exactly the water target.</p>
     */
    static final String TRANSPARENT_INK_FRAGMENT =
            "precision mediump float;\n"
            + "varying vec2 vWaterTextureCoord;\n"
            + "varying vec2 vBGTexture1Coord;\n"
            + "varying vec2 vBGScreenCoord;\n"
            + "varying vec3 vNormal;\n"
            + "varying vec3 vHalfVec;\n"
            + "varying float vHeights;\n"
            + "uniform sampler2D sWaterTexture;\n"
            + "uniform sampler2D sBGTexture;\n"
            + "uniform sampler2D Density;\n"
            + "uniform float alphaRatio1;\n"
            + "uniform float fresnelRatio;\n"
            + "uniform float specularRatio;\n"
            + "uniform float exponent;\n"
            + "uniform vec2 Scale;\n"
            + "uniform float intensity;\n"
            + "uniform vec3 ink_color;\n"
            + "uniform float uOverlayMaskLow;\n"
            + "uniform float uOverlayMaskHigh;\n"
            + "float sourceOverNeed(float baseChannel, float targetChannel) {\n"
            + "  if (targetChannel < baseChannel && baseChannel > 0.0)"
            + " return (baseChannel - targetChannel) / baseChannel;\n"
            + "  if (targetChannel > baseChannel && baseChannel < 1.0)"
            + " return (targetChannel - baseChannel) / (1.0 - baseChannel);\n"
            + "  return 0.0;\n"
            + "}\n"
            + "void main() {\n"
            + "  vec4 waterColor = texture2D(sWaterTexture, vWaterTextureCoord);\n"
            + "  vec3 refractedBG = texture2D(sBGTexture, vBGTexture1Coord).rgb;\n"
            + "  vec3 base = clamp(texture2D(sBGTexture, vBGScreenCoord).rgb, 0.0, 1.0);\n"
            + "  float NdotHV = max(dot(vNormal, vHalfVec), 0.0);\n"
            + "  float specular = clamp(specularRatio * pow(NdotHV, exponent), 1.0, 4.5);\n"
            + "  float NdotL = max(dot(vNormal, vec3(5.0, -5.0, 1.0)), 0.0);\n"
            + "  float t = clamp(abs(vHeights), 0.0, 1.13);\n"
            + "  vec3 rippleRGB = t * specular * waterColor.rgb"
            + " * (alphaRatio1 + fresnelRatio * clamp(NdotL - 0.99, 0.0, 0.3))"
            + " + refractedBG;\n"
            + "  vec4 density = texture2D(Density, gl_FragCoord.xy * Scale);\n"
            + "  float d = 255.0 * density.x + density.y;\n"
            + "  float w = intensity * d;\n"
            + "  float inkCoverage = clamp(w, 0.0, 1.0);\n"
            + "  vec3 waterTarget = clamp(rippleRGB, 0.0, 1.0);\n"
            + "  vec3 inkTarget = waterTarget;\n"
            + "  if (w > 0.0) {\n"
            + "    inkTarget = waterTarget * ink_color"
            + " / (ink_color + w * (vec3(1.5) - ink_color));\n"
            + "    if (ink_color.r == 0.0) inkTarget.r ="
            + " mix(waterTarget.r, inkTarget.r, inkCoverage);\n"
            + "    if (ink_color.g == 0.0) inkTarget.g ="
            + " mix(waterTarget.g, inkTarget.g, inkCoverage);\n"
            + "    if (ink_color.b == 0.0) inkTarget.b ="
            + " mix(waterTarget.b, inkTarget.b, inkCoverage);\n"
            + "  }\n"
            + "  inkTarget = clamp(inkTarget, 0.0, 1.0);\n"
            + "  float waterA = smoothstep(uOverlayMaskLow, uOverlayMaskHigh,"
            + " length(vNormal.xy));\n"
            + "  float effectiveWaterA = waterA + (1.0 - waterA) * inkCoverage;\n"
            + "  vec3 target = clamp(base + effectiveWaterA * (waterTarget - base)"
            + " + (inkTarget - waterTarget), 0.0, 1.0);\n"
            + "  vec3 needs = vec3(sourceOverNeed(base.r, target.r),"
            + " sourceOverNeed(base.g, target.g), sourceOverNeed(base.b, target.b));\n"
            + "  float alpha = clamp(max(max(needs.r, needs.g), needs.b), 0.0, 1.0);\n"
            + "  vec3 premul = clamp(target - (1.0 - alpha) * base,"
            + " vec3(0.0), vec3(alpha));\n"
            + "  gl_FragColor = vec4(premul, alpha);\n"
            + "}\n";

    private RippleInkPortGlesShaders() {
    }
}
