#include "ripple_gles_overlay_shader.h"

const char lle_ripple_overlay_normal_fragment_shader[] =
        "precision mediump float;\n"
        "varying vec2 vWaterTextureCoord;\n"
        "varying vec2 vBGTexture1Coord;\n"
        "varying vec3 vNormal;\n"
        "varying vec3 vHalfVec;\n"
        "varying float vHeights;\n"
        "uniform sampler2D sWaterTexture;\n"
        "uniform sampler2D sBGTexture;\n"
        "uniform float alphaRatio1;\n"
        "uniform float fresnelRatio;\n"
        "uniform float specularRatio;\n"
        "uniform float exponent;\n"
        "uniform float viewportHeight;\n"
        "uniform float uOverlayMaskLow;\n"
        "uniform float uOverlayMaskHigh;\n"
        "uniform float uOverlayOpacity;\n"
        "void main() {\n"
        "  float slopeStrength = length(vNormal.xy);\n"
        "  float mask = smoothstep(uOverlayMaskLow, uOverlayMaskHigh, slopeStrength) * uOverlayOpacity;\n"
        "  if (mask <= 0.0) {\n"
        "    gl_FragColor = vec4(0.0);\n"
        "    return;\n"
        "  }\n"
        "  vec4  waterColor = texture2D(sWaterTexture, vec2(vWaterTextureCoord.s, vWaterTextureCoord.t));\n"
        "  vec4  bgColor = texture2D(sBGTexture, vec2(vBGTexture1Coord.s, vBGTexture1Coord.t));\n"
        "  float NdotHV = max(dot(vNormal, vHalfVec),0.0);\n"
        "  float t = clamp(abs(vHeights), 0.0, 1.13);\n"
        "  float specular =  clamp(specularRatio * pow(NdotHV, exponent), 1.0, 5.5) ;\n"
        "  float NdotL = max(dot(vNormal, vec3(5.0,-5.0, 1.0)),0.0);\n"
        "  vec3  rippleRGB = t * specular* waterColor.rgb * ( alphaRatio1 +  fresnelRatio * clamp((NdotL - 0.99),0.0, 0.3)) + bgColor.rgb ;\n"
        "  vec3 samsungResult = clamp(rippleRGB, 0.0, 1.0);\n"
        "  gl_FragColor = vec4(mask * samsungResult, mask);\n"
        "}\n";
