#include "ripple_gles_overlay_shader.h"

const char lle_ripple_overlay_normal_fragment_shader[] =
        "precision mediump float;\n"
        "varying vec2 vWaterTextureCoord;\n"
        "varying vec2 vBGTexture1Coord;\n"
        "varying vec3 vNormal;\n"
        "varying vec3 vHalfVec;\n"
        "varying float vHeights;\n"
        "uniform sampler2D sWaterTexture;\n"
        "uniform sampler2D sBGTexture;\n"
        "uniform float alphaRatio1;\n"
        "uniform float fresnelRatio;\n"
        "uniform float specularRatio;\n"
        "uniform float exponent;\n"
        "uniform float viewportHeight;\n"
        "uniform float uOverlayMaskLow;\n"
        "uniform float uOverlayMaskHigh;\n"
        "uniform float uOverlayOpacity;\n"
        "void main() {\n"
        "  float slopeStrength = length(vNormal.xy);\n"
        "  float mask = smoothstep(uOverlayMaskLow, uOverlayMaskHigh, slopeStrength) * uOverlayOpacity;\n"
        "  if (mask <= 0.0) {\n"
        "    gl_FragColor = vec4(0.0);\n"
        "    return;\n"
        "  }\n"
        "  vec4  waterColor = texture2D(sWaterTexture, vec2(vWaterTextureCoord.s, vWaterTextureCoord.t));\n"
        "  vec4  bgColor = texture2D(sBGTexture, vec2(vBGTexture1Coord.s, vBGTexture1Coord.t));\n"
        "  float NdotHV = max(dot(vNormal, vHalfVec),0.0);\n"
        "  float t = clamp(abs(vHeights), 0.0, 1.13);\n"
        "  float specular =  clamp(specularRatio * pow(NdotHV, exponent), 1.0, 5.5) ;\n"
        "  float NdotL = max(dot(vNormal, vec3(5.0,-5.0, 1.0)),0.0);\n"
        "  vec3  rippleRGB = t * specular* waterColor.rgb * ( alphaRatio1 +  fresnelRatio * clamp((NdotL - 0.99),0.0, 0.3)) + bgColor.rgb ;\n"
        "  vec3 samsungResult = clamp(rippleRGB, 0.0, 1.0);\n"
        "  gl_FragColor = vec4(mask * samsungResult, mask);\n"
        "}\n";

const char lle_ripple_overlay_ink_fragment_shader[] =
        "precision mediump float;\n"
        "varying vec2 vWaterTextureCoord;\n"
        "varying vec2 vBGTexture1Coord;\n"
        "varying vec3 vNormal;\n"
        "varying vec3 vHalfVec;\n"
        "varying float vHeights;\n"
        "uniform sampler2D sWaterTexture;\n"
        "uniform sampler2D sBGTexture;\n"
        "uniform sampler2D Density;\n"
        "uniform float alphaRatio1;\n"
        "uniform float fresnelRatio;\n"
        "uniform float specularRatio;\n"
        "uniform float exponent;\n"
        "uniform vec2 Scale;\n"
        "uniform float intensity;\n"
        "uniform vec3 ink_color;\n"
        "uniform float uOverlayMaskLow;\n"
        "uniform float uOverlayMaskHigh;\n"
        "uniform float uOverlayOpacity;\n"
        "void main() {\n"
        "  vec4 waterColor = texture2D(sWaterTexture, vWaterTextureCoord);\n"
        "  vec4 bgColor = texture2D(sBGTexture, vBGTexture1Coord);\n"
        "  float NdotHV = max(dot(vNormal, vHalfVec), 0.0);\n"
        "  float specular = clamp(specularRatio * pow(NdotHV, exponent), 1.0, 4.5);\n"
        "  float NdotL = max(dot(vNormal, vec3(5.0, -5.0, 1.0)), 0.0);\n"
        "  float t = clamp(abs(vHeights), 0.0, 1.13);\n"
        "  vec3 rippleRGB = t * specular * waterColor.rgb * (alphaRatio1 + fresnelRatio * clamp((NdotL - 0.99), 0.0, 0.3)) + bgColor.rgb;\n"
        "  vec2 densityCoord = gl_FragCoord.xy * Scale;\n"
        "  vec4 density = texture2D(Density, densityCoord);\n"
        "  float d = 255.0 * density.x + density.y;\n"
        "  float w = intensity * d;\n"
        "  float slopeMask = smoothstep(uOverlayMaskLow, uOverlayMaskHigh, length(vNormal.xy));\n"
        "  vec3 samsungResult = clamp(rippleRGB / (1.0 + w * ink_color), 0.0, 1.0);\n"
        /* Use the minimum source-over alpha capable of reproducing Samsung's
         * target RGB over the cached base. A tiny density tail must not turn
         * into a fully opaque patch of the lockscreen screenshot. */
        "  vec3 base = clamp(bgColor.rgb, 0.0, 1.0);\n"
        "  vec3 darkNeed = max(base - samsungResult, 0.0) / max(base, vec3(0.001));\n"
        "  vec3 lightNeed = max(samsungResult - base, 0.0) / max(vec3(1.0) - base, vec3(0.001));\n"
        "  float deltaMask = max(max(max(darkNeed.r, darkNeed.g), darkNeed.b), max(max(lightNeed.r, lightNeed.g), lightNeed.b));\n"
        "  float mask = clamp(max(slopeMask, deltaMask) * uOverlayOpacity, 0.0, 1.0);\n"
        "  if (mask <= 0.0) { gl_FragColor = vec4(0.0); return; }\n"
        "  vec3 premul = clamp(samsungResult - (1.0 - mask) * base, vec3(0.0), vec3(mask));\n"
        "  gl_FragColor = vec4(premul, mask);\n"
        "}\n";
