#include "ripple_gles_shaders.h"

const int16_t lle_ripple_quad_vertices[16] = {
        -1, -1, 0, 0,
         1, -1, 1, 0,
        -1,  1, 0, 1,
         1,  1, 1, 1
};

const char lle_ripple_quad_vertex_shader[] =
        "attribute vec4 vertex;\n"
        "attribute vec2 texCoord;\n"
        "varying vec2 v_texCoord;\n"
        "void main()\n"
        "{\n"
        "    gl_Position = vertex;\n"
        "    v_texCoord = texCoord;\n"
        "}\n";

const char lle_ripple_advect_density_fragment_shader[] =
        "precision mediump float;\n"
        "uniform sampler2D VelocityTexture;\n"
        "uniform sampler2D SourceTexture;\n"
        "uniform vec2 TimeStep;\n"
        "uniform float BackwardStepSize;\n"
        "uniform float Dissipation;\n"
        "uniform vec2 Scale;\n"
        "uniform vec2 center;\n"
        "uniform int drag;\n"
        "varying vec2 v_texCoord;\n"
        "vec2 encode(float v)\n"
        "{\n"
        "    const vec2 mask = vec2(0.00392157, 1.0);\n"
        "    v = clamp(v, -127.0, 127.0);\n"
        "    vec2 p = fract(v*mask);\n"
        "    p.x -= p.y/255.0;\n"
        "    return p;\n"
        "}\n"
        "void main()\n"
        "{\n"
        "    vec2 fragCoord = gl_FragCoord.xy;\n"
        "    vec4 buf = texture2D(VelocityTexture, v_texCoord);\n"
        "    vec2 u;\n"
        "    u.x = 255.0*buf.x + buf.y - 127.0;\n"
        "    u.y = 255.0*buf.z + buf.w - 127.0;\n"
        "    float back_step = BackwardStepSize;\n"
        "    if(drag<2){\n"
        "        float d = distance(center, Scale*v_texCoord);\n"
        "        if( d < 80.0 ) back_step = 0.0075*d;\n"
        "    }\n"
        "    vec2 coord = v_texCoord - back_step * TimeStep * u;\n"
        "    buf = texture2D(SourceTexture, coord);\n"
        "    float value = 255.0*buf.x + buf.y;\n"
        "    gl_FragColor.xy = encode(Dissipation*value);\n"
        "}\n";

const char lle_ripple_add_ink_fragment_shader[] =
        "precision mediump float;\n"
        "uniform sampler2D Source;\n"
        "uniform vec2 Scale;\n"
        "uniform vec2 current;\n"
        "uniform vec2 previous;\n"
        "uniform vec2 normal;\n"
        "uniform int mode;\n"
        "uniform float len;\n"
        "uniform float ImpulseDensity;\n"
        "uniform float Radius;\n"
        "varying vec2 v_texCoord;\n"
        "vec2 encode(float v)\n"
        "{\n"
        "    v = clamp(v, -127.0, 127.0);\n"
        "    vec2 p;\n"
        "    p.x = fract(v/255.0);\n"
        "    p.y = fract(v);\n"
        "    p.x -= p.y/255.0;\n"
        "    return p;\n"
        "}\n"
        "void main()\n"
        "{\n"
        "    vec4 buf = texture2D(Source, v_texCoord);\n"
        "    float x = 255.0*buf.x + buf.y;\n"
        "    vec2 p = Scale*v_texCoord;\n"
        "    if(mode==2)\n"
        "    {\n"
        "        vec2 vector = p - previous;\n"
        "        float dot_val = dot(normal, vector);\n"
        "        if(dot_val > 0.0 && dot_val < len)\n"
        "        {\n"
        "            vec2 projected = previous + dot_val*normal;\n"
        "            float d = distance(projected, p);\n"
        "            if(d < Radius) x += ImpulseDensity*exp(-d*d/(0.8*Radius*Radius));\n"
        "        }\n"
        "    }\n"
        "    else\n"
        "    {\n"
        "        float d = distance(current, p);\n"
        "        if(d < Radius) x += ImpulseDensity/(1.0+d);\n"
        "    }\n"
        "    gl_FragColor.xy = encode(x);\n"
        "}\n";

const char lle_ripple_normal_vertex_shader[] =
        "uniform mat4 uMVPMatrix;\n"
        "attribute vec4 aPosition;\n"
        "attribute vec4 aHeights;\n"
        "varying vec2 vWaterTextureCoord;\n"
        "varying vec2 vBGTexture1Coord;\n"
        "varying vec3 vNormal;\n"
        "varying vec3 vHalfVec;\n"
        "varying float vHeights;\n"
        "uniform float uMESH_SIZE_WIDTH;\n"
        "uniform float uMESH_SIZE_HEIGHT;\n"
        "uniform float uNUM_DETAILS_WIDTH;\n"
        "uniform float uNUM_DETAILS_HEIGHT;\n"
        "uniform float uRefractiveIndex;\n"
        "void main() {\n"
        "    float maxX = uMESH_SIZE_WIDTH / 2.0;\n"
        "    float maxY = uMESH_SIZE_HEIGHT / 2.0;\n"
        "    float rimo = uRefractiveIndex - 1.0;\n"
        "    vec4 pos = aPosition;\n"
        "    vec4 heights = aHeights;\n"
        "    float len = heights.x;\n"
        "    vec3 v = vec3(pos.x, pos.y, len * 0.25);\n"
        "    vec2 n = (vec2(len) - heights.yz) * 0.25;\n"
        "    float nz = sqrt(dot(n, n) + 1.0);\n"
        "    n = n / nz;\n"
        "    vec3 d = vec3(v.x, v.y, v.z + 30.0);\n"
        "    len = sqrt(dot(d, d));\n"
        "    d = d / len;\n"
        "    float t = dot(d, vec3(n.x, n.y, 1.0)) * rimo;\n"
        "    d.x += n.x * t;\n"
        "    d.y += n.y * t;\n"
        "    float r0, u0, v0;\n"
        "    r0 = (30.9 - v.z) / d.z;\n"
        "    u0 = (d.x * r0 + v.x) / maxX * 0.25 + 0.5;\n"
        "    v0 = (d.y * r0 + v.y) / maxY * -0.25 + 0.5;\n"
        "    float uxx = n.x * 0.5 + 0.5 + pos.y / uMESH_SIZE_WIDTH * 0.25;\n"
        "    float vxx = n.y * 0.5 + 0.5 + pos.x / uMESH_SIZE_HEIGHT * 0.25;\n"
        "    vWaterTextureCoord = vec2(uxx, vxx);\n"
        "    vBGTexture1Coord = vec2(u0, v0);\n"
        "    vNormal = normalize(vec3(n.x, n.y, 0.6));\n"
        "    vHalfVec = normalize(normalize(vec3(0.0, 0.0, 1.0) - (uMVPMatrix * pos).xyz) + (uMVPMatrix * vec4(5.0, -5.0, 1.0, 1.0)).xyz);\n"
        "    vHeights = aHeights.x;\n"
        "    gl_Position = uMVPMatrix*pos;\n"
        "}\n";

const char lle_ripple_normal_fragment_shader[] =
        "precision mediump float;\n"
        "varying vec2 vWaterTextureCoord;\n"
        "varying vec2 vBGTexture1Coord;\n"
        "varying vec3 vNormal;\n"
        "varying vec3 vHalfVec;\n"
        "varying float vHeights;\n"
        "uniform sampler2D sWaterTexture;\n"
        "uniform sampler2D sBGTexture;\n"
        "uniform float alphaRatio1;\n"
        "uniform float fresnelRatio;\n"
        "uniform float specularRatio;\n"
        "uniform float exponent;\n"
        "uniform float viewportHeight;\n"
        "void main() {\n"
        "    vec4 waterColor = texture2D(sWaterTexture, vec2(vWaterTextureCoord.s, vWaterTextureCoord.t));\n"
        "    vec4 bgColor = texture2D(sBGTexture, vec2(vBGTexture1Coord.s, vBGTexture1Coord.t));\n"
        "    float NdotHV = max(dot(vNormal, vHalfVec),0.0);\n"
        "    float t = clamp(abs(vHeights), 0.0, 1.13);\n"
        "    float specular = clamp(specularRatio * pow(NdotHV, exponent), 1.0, 5.5);\n"
        "    float NdotL = max(dot(vNormal, vec3(5.0,-5.0, 1.0)),0.0);\n"
        "    vec3 rippleRGB = t * specular * waterColor.rgb * (alphaRatio1 + fresnelRatio * clamp((NdotL - 0.99),0.0, 0.3)) + bgColor.rgb;\n"
        "    gl_FragColor = vec4(rippleRGB, 1.0);\n"
        "}\n";

const char lle_ripple_ink_fragment_shader[] =
        "precision mediump float;\n"
        "uniform sampler2D Density;\n"
        "varying vec2 vWaterTextureCoord;\n"
        "varying vec2 vBGTexture1Coord;\n"
        "varying vec3 vNormal;\n"
        "varying vec3 vHalfVec;\n"
        "varying float vHeights;\n"
        "uniform sampler2D sWaterTexture;\n"
        "uniform sampler2D sBGTexture;\n"
        "uniform float alphaRatio1;\n"
        "uniform vec2 Scale;\n"
        "uniform float intensity;\n"
        "uniform vec3 ink_color;\n"
        "uniform float fresnelRatio;\n"
        "uniform float specularRatio;\n"
        "uniform float exponent;\n"
        "void main() {\n"
        "    vec4 waterColor = texture2D(sWaterTexture, vec2(vWaterTextureCoord.s, vWaterTextureCoord.t));\n"
        "    vec4 bgColor = texture2D(sBGTexture, vec2(vBGTexture1Coord.s, vBGTexture1Coord.t));\n"
        "    float NdotHV = max(dot(vNormal, vHalfVec),0.0);\n"
        "    float specular = clamp(specularRatio * pow(NdotHV, exponent), 1.0, 4.5);\n"
        "    float NdotL = max(dot(vNormal, vec3(5.0,-5.0, 1.0)),0.0);\n"
        "    float t = clamp(abs(vHeights), 0.0, 1.13);\n"
        "    vec3 rippleRGB = t * specular * waterColor.rgb * (alphaRatio1 + fresnelRatio * clamp((NdotL - 0.99),0.0, 0.3)) + bgColor.rgb;\n"
        "    vec4 buf = texture2D(Density, gl_FragCoord.xy * Scale);\n"
        "    float d = 255.0*buf.x + buf.y;\n"
        "    float w = intensity*d;\n"
        "    gl_FragColor = vec4(rippleRGB / (1.0+w*ink_color), 1.0);\n"
        "}\n";

const char lle_ripple_gravity_vertex_shader[] =
        "attribute vec4 aPosition;\n"
        "attribute vec4 aHeights;\n"
        "attribute vec2 aTextureU;\n"
        "varying vec2 vTexture0Coord;\n"
        "varying vec2 vTexture1Coord;\n"
        "varying vec2 vTextureBackCoord;\n"
        "varying vec2 vTextureCausticsCoord;\n"
        "varying float vHeights;\n"
        "varying vec3 vLightDir;\n"
        "varying vec3 vHoverI;\n"
        "varying vec3 vNormalI;\n"
        "varying vec3 vNormal;\n"
        "varying vec2 vTextureU;\n"
        "uniform mat4 uMVPMatrix;\n"
        "uniform mat4 uMVMatrix;\n"
        "uniform float uMESH_SIZE_WIDTH;\n"
        "uniform float uMESH_SIZE_HEIGHT;\n"
        "uniform float uNUM_DETAILS_WIDTH;\n"
        "uniform float uNUM_DETAILS_HEIGHT;\n"
        "uniform float uRefractiveIndex;\n"
        "uniform float uHoverX;\n"
        "uniform float uHoverY;\n"
        "uniform float uTexMove;\n"
        "uniform int uGravityDirection;\n"
        "varying vec3 vNormalL;\n"
        "varying vec3 vNormalHV;\n"
        "varying float vTexCoordU;\n"
        "void main() {\n"
        "    float maxX = uMESH_SIZE_WIDTH / 2.0;\n"
        "    float maxY = uMESH_SIZE_HEIGHT / 2.0;\n"
        "    float rimo = uRefractiveIndex - 1.1;\n"
        "    vec4 pos = aPosition;\n"
        "    vec4 heights = aHeights;\n"
        "    float len = heights.x;\n"
        "    vec3 v = vec3(pos.x, pos.y, len * 0.25);\n"
        "    vec2 n = (vec2(len) - heights.yz) * 0.25;\n"
        "    float nz = sqrt(dot(n, n) + 1.0);\n"
        "    n = n / nz;\n"
        "    vec3 d = vec3(v.x, v.y, v.z + 30.0);\n"
        "    len = sqrt(dot(d, d));\n"
        "    d = d / len;\n"
        "    vec3 d2 = d;\n"
        "    float t = dot(d, vec3(n.x, n.y, 1.0)) * rimo;\n"
        "    d.x += n.x * t;\n"
        "    d.y += n.y * t;\n"
        "    float r0, u0, v0;\n"
        "    r0 = (30.9 - v.z) / d.z;\n"
        "    u0 = (d.x * r0 + v.x) / maxX * 0.25 + 0.5;\n"
        "    v0 = (d.y * r0 + v.y) / maxY * -0.25 + 0.5;\n"
        "    float uxx = n.x * 0.5 + 0.5 + pos.y / uMESH_SIZE_WIDTH * 0.25;\n"
        "    float vxx = n.y * 0.5 + 0.5 + pos.x / uMESH_SIZE_HEIGHT * 0.25;\n"
        "    vTexture0Coord = vec2(uxx, vxx);\n"
        "    vTexture1Coord = vec2(u0, v0);\n"
        "    d2.x += n.x * (dot(d2, vec3(n.x, n.y, 1.0)) * (uRefractiveIndex - 0.3));\n"
        "    d2.y += n.y * (dot(d2, vec3(n.x, n.y, 1.0)) * (uRefractiveIndex - 0.3));\n"
        "    float causticsRefractx = (d2.x * r0 + v.x) / maxX * 0.25 + 0.5;\n"
        "    float causticsRefracty = (d2.y * r0 + v.y) / maxY * 0.25 + 0.5;\n"
        "    vTextureCausticsCoord = vec2(causticsRefractx, causticsRefracty);\n"
        "    vec3 v3 = vec3(pos.x, pos.y, heights.x * 0.001);\n"
        "    vec3 d3 = vec3(v3.x, v3.y, v3.z + 30.0);\n"
        "    float r3 = (30.9 - v3.z) / d3.z;\n"
        "    float Backx = ((d3.x * r3 + v3.x) / maxX * 0.25) + 0.5;\n"
        "    float Backy = ((d3.y * r3 + v3.y) / maxY * 0.25) + 0.5;\n"
        "    vTextureBackCoord = vec2(Backx, Backy);\n"
        "    vHoverI = normalize((uMVMatrix * (vec4(uHoverX, uHoverY, 12.0,1.0) - aPosition)).xyz);\n"
        "    vLightDir = normalize(vec3(70.0, 120.0, 1.0) - (uMVMatrix * aPosition).xyz);\n"
        "    vNormalI = normalize(vec3(0.0, 0.0, 1.0) - (uMVMatrix * aPosition).xyz);\n"
        "    vNormal = cross(vec3(1.0, 0.0, aHeights.x - aHeights.z), vec3(0.0, 1.0, aHeights.y - aHeights.x));\n"
        "    vHeights = aHeights.x;\n"
        "    vTextureU = aTextureU;\n"
        "    vNormalL = vLightDir;\n"
        "    vNormalHV = normalize(vNormalL + vNormalI);\n"
        "    if(uGravityDirection == 0){\n"
        "        vTexCoordU = (1.0 - vTextureBackCoord.x) + uTexMove;\n"
        "    } else {\n"
        "        vTexCoordU = vTextureBackCoord.x + uTexMove;\n"
        "    }\n"
        "    gl_Position = uMVPMatrix * pos;\n"
        "}\n";

const char lle_ripple_gravity_fragment_shader[] =
        "precision mediump float;\n"
        "varying float vHeights;\n"
        "varying vec2 vTexture0Coord;\n"
        "varying vec2 vTexture1Coord;\n"
        "varying vec2 vTextureBackCoord;\n"
        "varying vec2 vTextureCausticsCoord;\n"
        "varying vec3 vLightDir;\n"
        "varying vec3 vHoverI;\n"
        "varying vec3 vNormalI;\n"
        "varying vec3 vNormal;\n"
        "varying vec2 vTextureU;\n"
        "uniform sampler2D sWaterTexture;\n"
        "uniform sampler2D sBGTexture;\n"
        "uniform sampler2D gravityTexture;\n"
        "uniform sampler2D causticTexture;\n"
        "uniform sampler2D causticTexture2;\n"
        "uniform float alphaRatio1;\n"
        "uniform float alphaRatio2;\n"
        "uniform float fresnelRatio;\n"
        "uniform float specularRatio;\n"
        "uniform float exponent;\n"
        "uniform float uPercent;\n"
        "uniform float uCausticTimeMix;\n"
        "uniform float uCausticTimeRatio;\n"
        "uniform float uCausticTimeRatio2;\n"
        "uniform float uReferencePoint;\n"
        "uniform float uCausitcAni;\n"
        "uniform float uWaterbrightness;\n"
        "varying vec3 vNormalL;\n"
        "varying vec3 vNormalHV;\n"
        "varying float vTexCoordU;\n"
        "void main() {\n"
        "    float HeightAlphaMap = 0.0;\n"
        "    vec2 texHAMMap = vec2(vTexCoordU, vTextureBackCoord.t);\n"
        "    HeightAlphaMap += texture2D(gravityTexture, texHAMMap + vec2(0.0, 0.00208333333333333333333333333333*2.0)).r;\n"
        "    HeightAlphaMap += texture2D(gravityTexture, texHAMMap - vec2(0.0, 0.00208333333333333333333333333333*2.0)).r;\n"
        "    HeightAlphaMap += texture2D(gravityTexture, texHAMMap + vec2(0.0037037037037037037037037037037*2.0, 0.0)).r;\n"
        "    HeightAlphaMap += texture2D(gravityTexture, texHAMMap - vec2(0.0037037037037037037037037037037*2.0, 0.0)).r;\n"
        "    HeightAlphaMap *= 0.25;\n"
        "    vec3 rippleRGB;\n"
        "    vec4 texBackground = texture2D(sBGTexture, vec2(vTextureBackCoord.s, 1.0 - vTextureBackCoord.t));\n"
        "    float tex2Point = HeightAlphaMap * uReferencePoint + 20.0;\n"
        "    float HeightReferencePoint = vHeights + ((uReferencePoint - 40.0) * 0.2) + 46.0;\n"
        "    if(tex2Point <= HeightReferencePoint){\n"
        "        vec3 N = normalize(vNormal);\n"
        "        vec4 tex0 = texture2D(sWaterTexture, vec2(vTexture0Coord.s, vTexture0Coord.t));\n"
        "        vec4 tex1 = texture2D(sBGTexture, vec2(vTexture1Coord.s, vTexture1Coord.t));\n"
        "        float hoverSpecular = 0.0;\n"
        "        vec4 texCaustic = texture2D(causticTexture, vec2(vTextureCausticsCoord.s, vTextureCausticsCoord.t));\n"
        "        vec4 texCaustic2 = texture2D(causticTexture2, vec2(vTextureCausticsCoord.s, vTextureCausticsCoord.t));\n"
        "        float NdotHV = max(dot(N, vNormalHV),0.0);\n"
        "        float specular = specularRatio * pow(NdotHV, exponent);\n"
        "        if(uPercent > 0.0) {\n"
        "            NdotHV = max(dot(N, vHoverI), 0.0);\n"
        "            hoverSpecular = pow(NdotHV, max((uPercent), 60.0));\n"
        "        }\n"
        "        float NdotL;\n"
        "        if(uPercent > 0.1) {\n"
        "            NdotL = max(dot(N, vec3(-5.0, -5.0, 1.0)) + dot(N, vec3(5.0, 5.0, 1.0)), 0.0);\n"
        "        } else {\n"
        "            NdotL = max(dot(N, vec3(5.0, 5.0, 1.0)), 0.0);\n"
        "        }\n"
        "        float dirtyAlpha = clamp(abs(vHeights), 0.0, 1.13);\n"
        "        float causticRatio = min(abs(vHeights), 0.5) * 2.0;\n"
        "        vec3 causticMix = mix(texCaustic.rgb, texCaustic2.rgb, uCausticTimeMix);\n"
        "        float CausticsColorSum = 1.4 - clamp(abs(vHeights * 1.5), 0.2, 1.2);\n"
        "        float CausticsResult = (pow((CausticsColorSum - 0.2),3.0) * 0.2) + 0.9;\n"
        "        vec3 baseRippleRGB = vec3(specular) + vec3(max(hoverSpecular * uPercent * 0.9, 0.0)) + dirtyAlpha * tex0.rgb * (alphaRatio1 + (fresnelRatio + uPercent) * clamp((NdotL - 0.99),0.0, 0.3)) + tex1.rgb * alphaRatio2;\n"
        "        rippleRGB = baseRippleRGB + (causticMix * uCausticTimeRatio * causticRatio) + (pow(CausticsResult, 5.0) * tex1.rgb * abs(uCausticTimeRatio2) * 0.7);\n"
        "        if(tex2Point <= HeightReferencePoint && tex2Point >= HeightReferencePoint - 1.0){\n"
        "            float ratioMix = tex2Point - (HeightReferencePoint - 1.0);\n"
        "            rippleRGB = mix(rippleRGB * (0.6 + (0.4 * (1.0 - ratioMix))), texBackground.rgb * (0.6 + (0.4 * ratioMix)), ratioMix);\n"
        "        }\n"
        "    } else {\n"
        "        rippleRGB = texBackground.rgb;\n"
        "    }\n"
        "    gl_FragColor = vec4(rippleRGB,1.0);\n"
        "}\n";
